name: 'fatt installer'
author: philips-labs
description: 'An action to install fatt'
branding:
  icon: lock
  color: purple
inputs:
  fatt-release:
    description: 'fatt release version to be installed'
    required: false
    default: 'v0.2.0-rc2'
  install-dir:
    description: 'Where to install the fatt binary'
    required: false
    default: '$HOME/.fatt/bin'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: $GITHUB_ACTION_PATH/install.sh
      env:
        VERSION: ${{ inputs.fatt-release }}
        INSTALL_PATH: ${{ inputs.install-dir }}
    - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run:  echo "${{ inputs.install-dir }}" >> $GITHUB_PATH
      shell: bash
    - if: ${{ runner.os == 'Windows' }}
      run:  echo "${{ inputs.install-dir }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
